"""conta destino

Revision ID: 3ca68896566b
Revises: 
Create Date: 2023-12-23 15:05:41.245683

"""
from alembic import op
import sqlalchemy as sa
from backend.models.conta import Conta
from backend.models.pessoa import Pessoa
from sqlalchemy.orm import sessionmaker
from backend.models.transacao import Transacao
from backend.models.usuario import Usuario
from werkzeug.security import generate_password_hash    


# revision identifiers, used by Alembic.
revision = '3ca68896566b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('pessoa',
    sa.Column('id_pessoa', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_pessoa'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('conta',
    sa.Column('id_conta', sa.Integer(), nullable=False),
    sa.Column('id_pessoa', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('limite_saque_diario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('flag_ativo', sa.Boolean(), nullable=False),
    sa.Column('tipo_conta', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_pessoa'], ['pessoa.id_pessoa'], ),
    sa.PrimaryKeyConstraint('id_conta')
    )
    op.create_table('transacao',
    sa.Column('id_transacao', sa.Integer(), nullable=False),
    sa.Column('id_conta', sa.Integer(), nullable=False),
    sa.Column('id_conta_destino', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_transacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_conta'], ['conta.id_conta'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_conta_destino'], ['conta.id_conta'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_transacao')
    )
    # ### end Alembic commands ###
    pass_joao = generate_password_hash('joao123')
    pass_maria = generate_password_hash('maria123')
    pass_jose = generate_password_hash('jose123')

    Session = sessionmaker(bind=op.get_bind())
    session = Session()

    session.bulk_insert_mappings(Usuario,
    [
        {'id':1, 'username': 'joao', 'password': pass_joao },
        {'id':2, 'username': 'maria', 'password': pass_maria },
        {'id':3, 'username': 'jose','password': pass_jose },
    ])

    session.bulk_insert_mappings(Pessoa,
    [
        {'id_pessoa': 1, 'user_id':1, 'nome':'joao', 'cpf': '101.111.111-11', 'data_nascimento':'2002-12-06'},
        {'id_pessoa': 2, 'user_id':2, 'nome':'maria', 'cpf': '201.212.121-21', 'data_nascimento':'1981-09-06'},
        {'id_pessoa': 3, 'user_id':3,'nome':'jose', 'cpf': '301.311.131-13', 'data_nascimento':'1991-10-16'},
    ])

    session.bulk_insert_mappings(Conta,
    [
        {'id_conta':1, 'id_pessoa': 1, 'flag_ativo':True, 'tipo_conta':1,'saldo': 10000},
        {'id_conta':2, 'id_pessoa': 2, 'tipo_conta':2,'saldo': 50000},
        {'id_conta':3, 'id_pessoa': 3, 'tipo_conta':1,'saldo': 5000},
    ])
    # ### end Alembic commands ###
    session.bulk_insert_mappings(Transacao,
    [
        {'id_transacao':1, 'id_conta': 1,'id_conta_destino': 2 ,'valor': 1000},
        {'id_transacao':2, 'id_conta': 2,'id_conta_destino': 3 ,'valor': 1500},
        {'id_transacao':3, 'id_conta': 3,'id_conta_destino': 2 ,'valor': 500},
        {'id_transacao':4, 'id_conta': 1,'id_conta_destino': 1 ,'valor': 700},
        {'id_transacao':5, 'id_conta': 2,'id_conta_destino': 2 ,'valor': 50},
        {'id_transacao':6, 'id_conta': 3,'id_conta_destino': 1 ,'valor': 30},
    ])

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacao')
    op.drop_table('conta')
    op.drop_table('pessoa')
    op.drop_table('usuario')
    # ### end Alembic commands ###
